### ISSUE TITLE
[IOS]Error when run pod install

### ISSUE THREAD

**Issue by 2ducanhpham** [IGAWorksDev/react-native-adbrix-remaster#1]
I try run pod install but error

Step 1: yarn add react-native-adbrix-remaster
Step 2: react-native link react-native-adbrix-remaster
Step 3: cd ios && pod install

System: 
- React-native: 0.59.9
- Node: v11.0.0
- Cocoa Pod v1.7.3

![Screen Shot 2019-08-10 at 10 23 15 AM](https://user-images.githubusercontent.com/14899775/62816980-63103200-bb59-11e9-94b8-6b1dc540e99f.png)

**Comment by yen-igaw** [comment]
Giờ mới đọc mục này của Đức Anh kkk. Skip cái này nhé.
Pls notice that try latest SDK to avoid such issue. We have a dedicated help desk center, which is integrated in adbrix console. You can submit a new ticket here. https://help.adbrix.io/hc/vi/requests/new
All issue is fixed with latetest sdk. Please reference sdk version information to find suitable SDK. https://help.adbrix.io/hc/vi/articles/360006568953-SDK-Release-Note-iOS
