### ISSUE TITLE
Crash on iOS version < 12.0

### ISSUE THREAD

**Issue by tony-jpham** [IGAWorksDev/react-native-adbrix-remaster#2]
Hi, this error appear when i build on iOS simulator with iOS 11.2

dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/toanpham/Library/Developer/CoreSimulator/Devices/72758EA8-E31E-458D-BD28-EBFE065115E6/data/Containers/Bundle/Application/CB1095C5-C536-402B-B299-31619AB18D15/bTaskee.app/Frameworks/AdBrixRM.framework/AdBrixRM
  Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftAVFoundation.dylib: mach-o, but not built for iOS simulator
(lldb) 

Please check and fix them ASAP.

**Comment by yen-igaw** [comment]
Pls notice that try latest SDK to avoid such issue. We have a dedicated help desk center, which is integrated in adbrix console. You can submit a new ticket here. https://help.adbrix.io/hc/vi/requests/new
All issue is fixed with latetest sdk. Please reference sdk version information to find suitable SDK. https://help.adbrix.io/hc/vi/articles/360006568953-SDK-Release-Note-iOS
